language: python
python:
  - "3.7"
# command to install dependencies
install:
  - python setup.py install
  - pip install gitpython pylint
# command to run tests
script:
  - ./run_tests.py -v -t lint

